### ISSUE TITLE
CLI Documentation

### ISSUE THREAD

**Issue by ghost** [artus-analysis/Excalibur#11]
The documentation for Excalibur and Merlin available on the CLI is rather brief. This is especially apparent for Merlin (see https://github.com/artus-analysis/Artus/issues/7).

I'd suggest inclusion of important references into the `-h` options and the creation of man pages.

**Comment by dhaitz** [comment]
I have extended the merlin CLI documentation:
https://github.com/artus-analysis/Excalibur/commit/8bff7c41e
however most of the arguments are defined in HarryPlotter, not Merlin
