### ISSUE TITLE
Investigate muon isolation Data/MC differences

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#12]
http://www-ekp.physik.uni-karlsruhe.de/~dhaitz/plots_archive/2015_07_15/muoniso/overview.html

**Comment by ghost** [comment]
See plots directly from AOD generated by Dominik:
http://www-ekp.physik.uni-karlsruhe.de/~dhaitz/plots_archive/2015_08_13/muoniso_aod/overview.html

Objects used at merlin level:
http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_08_13/cuts_2015_nofilters/overview.html

**Comment by dhaitz** [comment]
can we close this?
