### ISSUE TITLE
Calculate mu in data ("npumeandata") 

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#19]
should be possible with brilcalc, see e.g. https://hypernews.cern.ch/HyperNews/CMS/get/luminosity/499.html

**Comment by JoramBerger** [comment]
Suggestion: call it `npumean` like in mc

**Comment by dhaitz** [comment]
renamed, see https://github.com/artus-analysis/Excalibur/commit/cc98e7c45

**Comment by dhaitz** [comment]
brilcalc lumi -b “STABLE BEAMS” -i JSON file -o outfile.txt

**Comment by dhaitz** [comment]
see https://indico.cern.ch/event/446471/contribution/30/attachments/1156389/1662454/Harrington_JERC_17092015.pdf

**Comment by ghost** [comment]
Added NPUProducer input txt producer script: https://github.com/artus-analysis/Excalibur/commit/063c1e71058fd27d0be85eec81b77537d70dd25c
Added npumean to data15: https://github.com/artus-analysis/Excalibur/commit/02c20853e5d4adf62063e84d49a88ebff3b64062
Fixed typo: https://github.com/artus-analysis/Excalibur/commit/c9131f7dc36f750dc522b4954081361ec75564b1
Updated min bias to Mikko's specs: https://github.com/artus-analysis/Excalibur/commit/ba6df9ae9c204f2fff48186fab6af091ca38fe40
