### ISSUE TITLE
Check JetID for 13 TeV

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#20]
check we're using the latest recommendations from 
https://twiki.cern.ch/twiki/bin/view/CMS/JetID#Recommendations_for_13_TeV_data

**Comment by JoramBerger** [comment]
This is now done and automatically turned on dfda19f1 using [`Artus:860aa7`](https://github.com/artus-analysis/Artus/commit/860aa77142a). Could Max or Christian please run it and see wether there are any changes w.r.t. the 73x ID (just comparing this to the latest sample you already have)?

**Comment by dhaitz** [comment]
I think Joram has implemented the latest ID recommendations
