### ISSUE TITLE
Differentiate between 25n and 50ns in defaultconfig

### ISSUE THREAD

**Issue by ghost** [artus-analysis/Excalibur#22]
The functions and templates in `configtools.py` and `defaultconfig.py` should be sensitive to 25ns data, with the default being 50ns.

**Comment by dhaitz** [comment]
this should be possible in the same way the 'tagged' argument is implemented

**Comment by ghost** [comment]
Configs for 2015 use an additional keyword since 3a16c6f and 02ecdf3 (data and mc).
