### ISSUE TITLE
Check jet response time dependence in 2015 data, esp. in endcap and forward

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#24]

**Comment by dhaitz** [comment]
see https://github.com/artus-analysis/Artus/commit/67e0efd3b and https://github.com/artus-analysis/Excalibur/commit/f0529820
one would have to add the values for 2015 data

**Comment by ghost** [comment]
Run ranges for 2015 A-D have been added in https://github.com/artus-analysis/Artus/commit/f9f7ed21860e9ef758ed30265cea2b363291bd60.

**Comment by ghost** [comment]
Time dependence plots are [working](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_10_22/rtd_25/overview.html).
