### ISSUE TITLE
Change in muon-jet veto procedure

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#25]
right now we have the DeltaR cut that Max activated. However, this might veto ALL jets containing muons, e.g. reject b-jets with a small muon fraction from semileptonic b decays.
- maybe only veto on jet muon fraction?
- maybe only veto on the muons from Z decay, not all valid muons?

**Comment by joram-berger** [comment]
The difference between vetoing all muons (via deltaR) and the loose ID + lepton veto in the jet ID has been studied by Max. @MaxFischer-KIT can you link some plots here? The difference is very small, the big difference is when using the 2015 jet ID without any lepton rejection: this is completely unusable.
Nonetheless, I would suggest to only copy the muons of the Z to the m_validLeptons list and thus only veto these. This would imply our own derived valid lepton producer.

**Comment by JoramBerger** [comment]
The difference between vetoing all muons (via deltaR) and the loose ID + lepton veto in the jet ID has been studied by Max. @MaxFischer-KIT can you link some plots here? The difference is very small, the big difference is when using the 2015 jet ID without any lepton rejection: this is completely unusable.

Nonetheless, I would suggest to only copy the muons of the Z to the m_validLeptons list and thus only veto these. This would imply our own derived valid lepton producer.

**Comment by dhaitz** [comment]
We could also introduce a dedicted product member m_decayLeptons. This could also solve other problems: right now we take e.g. for muminus/muplus quantities the first negative/positive muon in m_validMuons, which might not be the muon from Z decay ...

**Comment by joram-berger** [comment]
The valid muons producer requires to use m_validLeptons – otherwise we must rewrite the muon ID, too.

**Comment by JoramBerger** [comment]
The valid jets producer requires to use m_validLeptons – otherwise we must rewrite the jet ID, too.

**Comment by ghost** [comment]
Plots for reference: [deltaR(jet1, mu1)](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_09_18/jid2_delta_r%28jet1,mu1%29_nocuts_mc.png),  [deltaR(jet1, mu1) finalcuts](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_09_18/jid2_delta_r%28jet1,mu1%29_finalcuts_mc.png), [deltaR(jet1, Z)](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_09_18/jid2_delta_r%28jet1,z%29_nocuts_mc.png)

As you can see, the plain 2015 JetID is useless as the leading muon and leading jet will be the same object in most cases. Using the lepveto and deltaR veto gets roughly the same statistics.

2cents: the use of 2015R3 and 2015lepveto is purely to veto Z muons for jet1 and jet2. Both options have side-effects from other muons and for other jets; for jets we cannot remove these effects as that would invalidate pT ordering. The proper approach therefore seems to limit the jet veto to the Z muons.
IMO this means:
1a) produce an explicit Z muons collection
1b) produce jets with any settings you want
2) re-produce the validJets, applying a deltaR veto against the Z muons only

**Comment by ghost** [comment]
Based on the Z decay leptons (available with https://github.com/artus-analysis/Excalibur/commit/cfa76bcbbb3b4f1036960cd53ea6bcd9dc1042e8) I have added a reprocessing step that vetoes jets close to Z decay leptons only. See test plots [here](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_09_23/jetid/overview.html).

The quantities are very similar to the all-muons-deltaR3 and lepton veto. However, [deltaPhi(jet1,-Z)](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_09_23/jetid/jid2_delta_phi%28jet1,-z%29_nocuts_mc.png) is higher for the new veto. This reduces [finalcuts events](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_09_23/jetid/jid2_delta_phi%28jet1,-z%29_finalcuts_mc.png) by about x10, as the BackToBack cut is much more severe.
I do not understand yet where this difference is coming from. Individual quantities match almost perfectly, but the deltaR/Eta/Phi show worse balancing. The new veto is available in https://github.com/artus-analysis/Excalibur/commit/f86e99d15e26d249f6774cf6fc633d3177839d03 but disabled by default.

**Comment by ghost** [comment]
Some bug fixes later... [results](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_09_24/jetid/overview.html) of the new veto (ZR3) are very similar to the old deltaR cut (R3). If there are no objections, I will make the veto the default for the mm channel.

**Comment by JoramBerger** [comment]
Yes please. Then you can close this issue. It would make sense to update the tests.

**Comment by ghost** [comment]
The new ZllJetVeto is now turned on by default. Since it requires a new producer sequence and I'm not familiar with non-mm channels, it is only active for mm at the moment.

Note that the test cases from 73X have passed.
