### ISSUE TITLE
Fix jet composition plots

### ISSUE THREAD

**Issue by JoramBerger** [artus-analysis/Excalibur#26]
The jet composition [plots](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_09_16/comparison_run2_50ns_jid73x/PFcontributions_abs%28jet1eta%29.png) show the HF neutral hadron fraction twice. Should be kept configurable for pre CMSSW 7.3.X samples

**Comment by dhaitz** [comment]
This wasnt properly fixed with https://github.com/artus-analysis/Excalibur/commit/cf8c930ef9c43 (missing configurability), but should now be fixed with https://github.com/artus-analysis/Excalibur/commit/54bfa77005
