### ISSUE TITLE
Muons in non-Muons Puppi

### ISSUE THREAD

**Issue by ghost** [artus-analysis/Excalibur#29]
Puppi provides best results when computed without muons. This requires muons to be completely removed from the Puppi collection during skimming before doing any computations. Muons should be added again after the Puppi veto and all derived quantities have been calculated.

**Comment by ghost** [comment]
This should be covered by https://github.com/KappaAnalysis/Kappa/commit/53a685c884760cca27a26e73242ba8631485dfdd now. Christian has created validation plots for [Puppi vs CHS](http://www-ekp.physik.uni-karlsruhe.de/~cmetzlaff/plots_archive/2015_09_17/comparison_CHS_PuppiNoMuNoHF_mpf_corrected_finalcuts_L1L2L3/overview.html) and [Data vs MC](http://www-ekp.physik.uni-karlsruhe.de/~cmetzlaff/plots_archive/2015_10_11/comparison_Puppi_datamc/overview.html).

**Comment by ghost** [comment]
Provided that the updated skim delivers expected results, I'd opt for removing the [muon MET workaround](https://github.com/artus-analysis/Excalibur/blob/master/src/Producers/TypeIMETProducer.cc#L55) entirely. If there are no objections I'll remove the section after validation of the skim.

**Comment by JoramBerger** [comment]
How about a comparison between "adding muons back in skim" and "adding muons back in Artus"? Wouldn't that be easy to do and should yield identical results?

**Comment by ghost** [comment]
There might be some changes in the jets (muons are re-added before constructing jets), but that _should_  be covered by the JetID. From a quick glance at Christians plots ([old](http://www-ekp.physik.uni-karlsruhe.de/%7Ecmetzlaff/plots_archive/2015_09_17/comparison_CHS_PuppiNoMuNoHF_mpf_corrected_finalcuts_L1L2L3/overview.html), [new](http://www-ekp.physik.uni-karlsruhe.de/~cmetzlaff/plots_archive/2015_10_10/comparison_CHS_PuppiNoMuNoHF_mpf_corrected_finalcuts_L1L2L3/overview.html)) there are some changes, but those also affect CHS. @christian are you available to quickly do a comparison between 25ns MC for old and new skims (`/storage/a/mfischer/skims/zjet/2015_09_26/` vs. `/storage/a/mfischer/skims/zjet/2015-10-09/`)?

**Comment by JoramBerger** [comment]
This should be checked on the common events. Did we miss to reenter the muons in the MET? It looks strange: [old](http://www-ekp.physik.uni-karlsruhe.de/~cmetzlaff/plots_archive/2015_09_17/comparison_CHS_PuppiNoMuNoHF_mpf_corrected_finalcuts_L1L2L3/met_shapeComparison.png), [new](http://www-ekp.physik.uni-karlsruhe.de/~cmetzlaff/plots_archive/2015_10_10/comparison_CHS_PuppiNoMuNoHF_mpf_corrected_finalcuts_L1L2L3/met_shapeComparison.png).

**Comment by ghost** [comment]
Sorry, not sure whether I picked the correct plot collections. @weltensurfer can you clarify whether both I picked have the muons added back in again?

**Comment by weltensurfer** [comment]
Plots from 2015_09_17 have the muons added at the plotting step only for some plots (not met plot)

Plots with muons readded by excalibur are here: http://www-ekp.physik.uni-karlsruhe.de/~cmetzlaff/plots_archive/2015_10_08/comparison_CHS_PuppiNoMuNoHF_finalcuts_L1L2L3/

I try to get the comparisons for 25ns done until tomorow.

**Comment by weltensurfer** [comment]
I've made the comparison 25ns MC for old and new skims (/storage/a/mfischer/skims/zjet/2015_09_26/ vs. /storage/a/mfischer/skims/zjet/2015-10-09/)

For the old skim I've subtracted 1 from MPF for the most plots.
Plots are here:
http://www-ekp.physik.uni-karlsruhe.de/~cmetzlaff/plots_archive/2015_10_14/comparison_Puppi_25ns_oldnew/overview.html

**Comment by ghost** [comment]
Closing this issue since the new collections behave better than the old ones.
