### ISSUE TITLE
reco vs ptcl in extrapolation not working

### ISSUE THREAD

**Issue by ghost** [artus-analysis/Excalibur#31]
I am unable to get the `reco vs ptcl` in the extrapolation plot working. It always gives a `1+1x` [result](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_10_07/comparison_V5/extrapolation.png).

I've created a patch that automatically extracts the actual input files (instead of wrongly hardcoded ones) but that seems to have no effect either.
[extra_diff.txt](https://github.com/artus-analysis/Excalibur/files/9687/extra_diff.txt)

My current guess is that it's a problem with undefined values not being filtered out.

**Comment by ghost** [comment]
Fixed with 64e7223. `args` had to be adjusted as well to contain the modified input file sequence expansion.

**Comment by dhaitz** [comment]
I suppose this has something to do with the expansion of the 'files' list. in your [config](http://www-ekp.physik.uni-karlsruhe.de/~mfischer/plots_archive/2015_10_07/comparison_V5/extrapolation.json) you have two files which will be expanded to ["data,mc,data,mc,data"]. However, the y-expressions are ["ptbalance", "ptbalance", "mpf", "mpf", "jet1pt/matchedgenjet1pt"]. The combination fo "data" and  "jet1pt/matchedgenjet1pt" will likely fail.

**Comment by dhaitz** [comment]
ah too late ;)
