### ISSUE TITLE
Use latest Type-I corrections

### ISSUE THREAD

**Issue by JoramBerger** [artus-analysis/Excalibur#33]
There might be changes in the Type-I correction: "now using ak4PFJetsCHS with pt > 15GeV (before it was ak4PFJets with pt > 10 GeV)". Raphael confirms this.
We should follow the official code.

**Comment by dhaitz** [comment]
link to official code?

**Comment by ghost** [comment]
Just to check back so that I don't miss anything: we're talking only about setting the cfg corresponding to [this](https://github.com/artus-analysis/Excalibur/blob/master/src/Producers/TypeIMETProducer.cc#L46) switch, correct?

**Comment by JoramBerger** [comment]
Yes, that's what I mean.
The current configuration is here: https://github.com/cms-sw/cmssw/blob/0876af31904e6ef56db62a4f23784261269d86a6/JetMETCorrections/Type1MET/python/correctionTermsPfMetType1Type2_cff.py#L41
It confirms the 15 GeV threshold.
