### ISSUE TITLE
Implement Z->ee for 2015 data and MC

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#38]
a test file to run on can be found here: /storage/8/dhaitz/testfiles/skim_74_mc_ee.root

**Comment by ghost** [comment]
The full skim is being streamed to `/storage/a/mfischer/skims/zjet/2015-10-21/` and should trickle in over the next few hours.

**Comment by ghost** [comment]
From what I've seen, this seems to work quite well so far. At the plotting level, Zee and Zmm seem to be largely identical. I'd suggest doing some consolidation, e.g. via https://github.com/artus-analysis/Excalibur/issues/37.
