### ISSUE TITLE
re-implement PU reweighting

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#4]

**Comment by dhaitz** [comment]
please reactivate the script to create the weightfiles

**Comment by JoramBerger** [comment]
On which basis? pileupCalc in old versions? I think it still works, the question is what should it do?

**Comment by dhaitz** [comment]
yes, I think at least for reproducing the 2012 PU reweighting

**Comment by ghost** [comment]
I cannot run puWeightCalc.py properly since it is looking for a hardcoded name in the skim:

```
puWeightCalc.py data/json/Cert_246908-258159_13TeV_PromptReco_Collisions15_25ns_JSON_v3.txt /storage/a/mfischer/skims/zjet/2015-10-09/DYJetsToLL_M_50_aMCatNLO_Asympt25ns_13TeV/*.root --inputLumiJSON /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/13TeV/PileUp/pileup_latest.txt
[stuff]
MC pile-up distribution from skim (1008 files): /storage/a/mfischer/skims/zjet/2015-10-09/DYJetsToLL_M_50_aMCatNLO_Asympt25ns_13TeV/kappa_DYJetsToLL_M_50_aMCatNLO_Asympt25ns_13TeV_1893.root etc.
Error in <TTreeFormula::Compile>:  Bad numerical expression : "KEventMetadata.numPUInteractionsTruth"
[stuff]
```

pileupCalc.py itself is working fine:

```
pileupCalc.py -i data/json/Cert_246908-258159_13TeV_PromptReco_Collisions15_25ns_JSON_v3.txt --inputLumiJSON /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/13TeV/PileUp/pileup_latest.txt --calcMode true --minBiasXsec 69000 --maxPileupBin 50 --numPileupBins 50 MyDataPileupHistogram.root
```

**Comment by JoramBerger** [comment]
Hardcoded sounds so bad. This was the Kappa 1 data format: "KEventMetadata.numPUInteractionsTruth" it should be "eventInfo.nPUMean" now in the [KEventInfo](https://github.com/KappaAnalysis/Kappa/blob/master/DataFormats/interface/KInfo.h#L117) of Kappa 2.

**Comment by JoramBerger** [comment]
Kappa content change is [fixed](https://github.com/artus-analysis/Artus/commit/b094ebc818167666c95e9ceee356cff02df3f1aa).

**Comment by ghost** [comment]
I've added some config utilities to handle the dependencies between data and MC (https://github.com/artus-analysis/Excalibur/commit/2eab9f4481ed165381cc5a7c54cd818db32cdcfa). They are used by default for 2015 25ns (https://github.com/artus-analysis/Excalibur/commit/37fcfc0dfc7f211322d8512a14fe9bf5e24b076d).

Some settings that were previously data only are now used for calculating the weights. I've moved `JsonFiles`, `Minbiasxsec` and `NPUFile` to the general config for 2015.

I'm aware that the new classes may seem like a **lot** of effort for setting simple configuration values. The alternative was juggling several internal and external dependencies by hand or having lots of boilerplate code that does almost the same every time. The current approach should be much more resistant to misconfiguration. If anybody has questions/concerns regarding design, implementation or usage of the new functionality, please let me know.
