### ISSUE TITLE
clean up pipeline name references

### ISSUE THREAD

**Issue by ghost** [artus-analysis/Excalibur#40]
We currently have a mixture of different naming conventions for pipelines in Excalibur and Merlin, as well as between different versions of each. This should be the mostly (exclusively) the "ak5" vs "AK5" naming.  We should unify this in all configs and application.

See also issue #39 on renaming the pipelines. Ideally, both should be done at the same time.

**Comment by JoramBerger** [comment]
Yes, pipeline names see #39. In general, the renaming should follow CMSSW and Kappa conventions: ak4 (not AK4), ak4PFJets(CHS|Puppi). In addition, in Artus, the 'TaggedJets' should be renamed to 'Jets'.

**Comment by dhaitz** [comment]
should we drop "Jets" and the algorithm name altogether? since theres only one algorithm per output file anyway we dont need to have the algorithm in every pipeline name

**Comment by JoramBerger** [comment]
Yes, that's mentioned in the often cited issue #39. The rest of my comment was just a general remark for other places. — welcome back, Dominik!
