### ISSUE TITLE
Strange responses

### ISSUE THREAD

**Issue by JoramBerger** [artus-analysis/Excalibur#45]
http://www-ekp.physik.uni-karlsruhe.de/~cmetzlaff/plots_archive/2015_12_07/puppi_jet_response_uncertainties/mpf_zpt_300-1000.png

We have a slight peak (ok, some events) at R = 0.5 and some around 2. Do you understand these? They can influence the mean and the fit. Is this in all Zpt bins? We should definitely look at all those. Also at over- and underflow bins.

**Comment by dhaitz** [comment]
I selected the events with MPF<0.5, they have a rather high MET:
http://www-ekp.physik.uni-karlsruhe.de/~dhaitz/plots_archive/2015_12_08/strange/_overview.html
Could be events with neutrinos emerging from the jet (c/b jets) or background (ttbar)

**Comment by dhaitz** [comment]
Raphael suggested this could be due to missing MET filters
https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2
