### ISSUE TITLE
Cleanup PUPPI workarounds

### ISSUE THREAD

**Issue by ghost** [artus-analysis/Excalibur#46]
There is apparently some leftover code from initial workarounds for various PUPPI issues. For example, there is a barely documented option to add muons to MET (https://github.com/artus-analysis/Excalibur/commit/80bd3c684174b4df53da9b7ce15a80a0ea2a4974). Merlin configs possibly have some legacy code as well.

I'd opt for removing any such leftovers on sight, unless they are used somewhere.

**Comment by dhaitz** [comment]
commit has been reverted
