### ISSUE TITLE
Kappa 2 support

### ISSUE THREAD

**Issue by ghost** [artus-analysis/Excalibur#47]
Excalibur can in principle digest Kappa 2 skims using the old interfaces. However, important features such as [KGenParticle.pdgId](https://github.com/KappaAnalysis/Kappa/blob/master/DataFormats/interface/KParticle.h#L13) have changed. It is not possible to use Excalibur with the required https://github.com/artus-analysis/Artus/tree/Kappa_2_1.

**Comment by ghost** [comment]
Joram's branch [Kappa_2_1](https://github.com/artus-analysis/Excalibur/tree/Kappa_2_1) seems to work fine with the new skims. I'd suggest to merge it into mater ASAP.

**Comment by dhaitz** [comment]
Hi Max, one problem is that we would use compatibility with all our old skims.
I think GeorgS or Fabio were proposing Kappa_2_1_1 reintroducing the pdgId() function and typedefs for the MET. This would mean that one can use the same Artus master with Kappa_2_0 skims (for us) and Kappa_2_1_1 skims (Higgs group who reskim all their data). Of course this would also mean you'd have to reskim the 76X samples with the previous Kappa_2_0. I think the Higgs group needs the new members in Kappa 2_1, however we gain nothing.

**Comment by ghost** [comment]
Perhaps we can discuss face-to-face the need for backwards compatibility in the master. Is there a need to run the new version over older skims?
I don't see any technical advantage from using K21 either. However, I would strongly oppose having to juggle so many additional branches (be they git or code).

**Comment by ghost** [comment]
We haven't had any changes on master in a while. It seems that only Kappa_2_1 is used actively, with legacy analyses using fixed master versions.
Unless there are any objections until after the DPG, I will tag the current master and merge branch Kappa_2_1 into master.

**Comment by dhaitz** [comment]
no objections from my side

**Comment by ghost** [comment]
I've merged `Kappa_2_1` into master with commit a31fe39. Excalibur seems to build fine, yet the travis tests are outdated.
I'd like to delete the `Kappa_2_1` branch in a few days (end of march?) if there is no unexpected behavior following this merge.

There is now a tag for the last working commit for Kappa 2.0, named `Kappa_2_0` (8f19401). Please use this version if you are still working on older skims.
