### ISSUE TITLE
MuonID und JetID fuer Run2 checken

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#5]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetID
https://twiki.cern.ch/twiki/bin/viewauth/CMS/SWGuideMuonIdRun2

**Comment by GeorgFleig** [comment]
Tight MuonID 2015 now implemented in Artus and enabled in Excalibur by default.
JetID still needs some checking of HF hadron fraction (Joram is on it)

**Comment by GeorgFleig** [comment]
JetID now set to "loose"

**Comment by JoramBerger** [comment]
Jet IDs now up-to-date. You need to update Excalibur **and** Artus to the new master. Current jet ID version is now 73Xtemp containing latest private JMAR recommendations (no ID for |eta|>3). To be used until the HF region is understood and 73X (=twiki) can be default again.

**Comment by JoramBerger** [comment]
Georg says MuonID is done. JetID is done, too.
