### ISSUE TITLE
Gen Z Production

### ISSUE THREAD

**Issue by annafriedel** [artus-analysis/Excalibur#51]
I changed the ZJetTreeConsumers genlevel outputs to work either with the GenZProducer included for testing or with [Artus GenBosonProducers](https://github.com/artus-analysis/Artus/blob/master/KappaAnalysis/src/Producers/GenBosonProducers.cc). I will remove the GetGenZ method from ZJetProduct in some days, because it isn't working correctly with actual CMSSW MC.

**Comment by HerrHorizontal** [comment]
No contributions for a long time, no one assigned. This issue will probably never carried on with. Therefore I close it.
