### ISSUE TITLE
PassKinCuts doesn't work...

### ISSUE THREAD

**Issue by annafriedel** [artus-analysis/Excalibur#52]
I tried to implement Artus' PassKinCuts Method in the[ ZJetGenParticlesProducer](https://github.com/artus-analysis/Excalibur/blob/master/Compile/src/Producers/ZJetGenParticleProducer.cc#L51) but for some reason, it always returns true, even with 
cfg['GenMuonLowerPtCuts'] = ['27']
cfg['GenMuonUpperAbsEtaCuts'] = ['2.3'] aplied. Has someone an idea, whats wrong here?

**Comment by HerrHorizontal** [comment]
No progress since three years. No one responsible. @annafriedel has left the group. I close the issue.
