### ISSUE TITLE
No default behaviour for th ZJetGenWeightProducer

### ISSUE THREAD

**Issue by HerrHorizontal** [artus-analysis/Excalibur#56]
In case of a configuration of Excalibur, where GenWeights are requested (https://github.com/KIT-CMS/Excalibur/blob/GENWeights/Compile/src/Producers/ZJetGenWeightProducer.cc#L49-L54), but the according skims do not provide the necesary information (due to older skims, wrong configuration), Excalibur should write default weights `1.0` into the requested weights.

**Comment by HerrHorizontal** [comment]
You can find the corresponding skimming code in https://github.com/KIT-CMS/Kappa/blob/GenWeights/DataFormats/interface/KInfo.h#L174-L179

**Comment by dsavoiu** [comment]
I guess for this to work, you would need to check if the index exists in [`getLheWeight`](https://github.com/KIT-CMS/Kappa/blob/e897c3a701544abeb6079635dbcfdf2179ae3f61/DataFormats/interface/KInfo.h#L174-L179) and return `1.0` if it doesn't (or throw an exception if `failOnError` is set).
