### ISSUE TITLE
Puppi jets checken

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#6]

**Comment by GeorgFleig** [comment]
Also check for Puppi MET (PUPPET) in skim and add it here: https://github.com/artus-analysis/Excalibur/blob/master/python/ZJetConfigBase.py#L47

**Comment by dhaitz** [comment]
make resolution plot comparing jets , CHS jets and PUPPI jets

**Comment by ghost** [comment]
New skims now include PUPPET. See [Zmm Twiki](http://www-ekp.physik.uni-karlsruhe.de/twiki/bin/view/EkpCms/Zmumujetanalysis) for current skims.

**Comment by dhaitz** [comment]
evtl praesentation im Do EKP meeting?

**Comment by dhaitz** [comment]
PUPPI Correction files now available at
http://people.physics.tamu.edu/delgado_andrea/CMS_JEC/index.php?path=Summer15_50nsV2_MC%2Ftxts%2FSummer15_50nsV2_MC_txts_fromDB/

**Comment by dhaitz** [comment]
can we close this?

**Comment by ghost** [comment]
We still have the open issue of muons obviously not being in the puppy-without-muons-collections. New issue or does it belong here?
