### ISSUE TITLE
add new pipeline to artus with beta cut instead of alpha cut

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#8]

**Comment by dhaitz** [comment]
is this still relevant? did we get a conclusion from the 'beta cut' studies?

**Comment by weltensurfer** [comment]
There is no conclusion until now. Needs to be done in the future.

We could remove the pipleline from the actual configs until it is needed.

**Comment by dhaitz** [comment]
voting for closing this issue

**Comment by ghost** [comment]
Closing this since there seems to be no specific plans for it. If needed in the future, please create a new issue.
